// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAx28-Sk99O3aBJ6dmOQA1ciQ4n0W2PCrU',
    appId: '1:1024869967272:web:8bd77563f8ebf7785b699d',
    messagingSenderId: '1024869967272',
    projectId: 'meudentinho-57d84',
    authDomain: 'meudentinho-57d84.firebaseapp.com',
    storageBucket: 'meudentinho-57d84.appspot.com',
    measurementId: 'G-0005Y864J4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD82A2u3027OM0DtklNYOIQH-kMrD8TlB0',
    appId: '1:1024869967272:android:09c8cac730c197c45b699d',
    messagingSenderId: '1024869967272',
    projectId: 'meudentinho-57d84',
    storageBucket: 'meudentinho-57d84.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOB-O4Z63NEro6L3LgfHq7lS-H-lvx4DI',
    appId: '1:1024869967272:ios:ca6f63e1f138a76d5b699d',
    messagingSenderId: '1024869967272',
    projectId: 'meudentinho-57d84',
    storageBucket: 'meudentinho-57d84.appspot.com',
    iosClientId: '1024869967272-t98s8bgipjfa1c6ulj3ek8vcj9g5ck7u.apps.googleusercontent.com',
    iosBundleId: 'com.example.meudentinho',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOB-O4Z63NEro6L3LgfHq7lS-H-lvx4DI',
    appId: '1:1024869967272:ios:ca6f63e1f138a76d5b699d',
    messagingSenderId: '1024869967272',
    projectId: 'meudentinho-57d84',
    storageBucket: 'meudentinho-57d84.appspot.com',
    iosClientId: '1024869967272-t98s8bgipjfa1c6ulj3ek8vcj9g5ck7u.apps.googleusercontent.com',
    iosBundleId: 'com.example.meudentinho',
  );
}
